name: Fossa Action
description: Actions for running FOSSA scans
author: Sora Morimoto
branding:
  icon: package
  color: gray-dark
inputs:
  fossa-api-key:
    required: true
  github-token:
    required: false
    default: ${{ github.token }}
  endpoint:
    required: false
  skip-test:
    required: false
    default: true
runs:
  using: node20
  main: dist/index.js
