name: Dependency Review

on: pull_request

permissions: read-all

jobs:
  dependency-review:
    name: Dependency Review

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Dependency Review
        uses: actions/dependency-review-action@0c155c5e8556a497adf53f2c18edabf945ed8e70 # v4.3.2
