name: Dependency Review

on: pull_request

permissions: read-all

jobs:
  dependency-review:
    name: Dependency Review

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Dependency Review
        uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c # v4.3.4
